### ISSUE TITLE
node-gyp rebuild error 'nan' module not found

### ISSUE THREAD

**Issue by shrikrishnaholla** [ncb000gt/node.bcrypt.js#428]
Node 6.2.1, Linux 4.1.19 debian, gcc 4.9.2, build-essential 11.7, Python 2.7.9

https://gist.github.com/shrikrishnaholla/5674d9b846b0a46cb4302a0b75139b14

The bcrypt build script fails with `Cannot find module 'nan'`, even when `nan` is globally installed. Works with node v5.11.1, everything else being same.

**Comment by leyyinad** [comment]
Same here, running on Ubuntu inside Docker:
```docker
FROM jedisct1/phusion-baseimage-latest
ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update
RUN curl -sL https://deb.nodesource.com/setup_6.x | bash -
RUN apt-get install -yq nodejs python # && npm install -g node-gyp
RUN npm install bcrypt
```

resulting in:

```
> bcrypt@0.8.7 install /node_modules/bcrypt
> node-gyp rebuild

module.js:442
    throw err;
    ^
Error: Cannot find module 'nan'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at [eval]:1:1
    at Object.exports.runInThisContext (vm.js:54:17)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:541:32)
    at node.js:311:29
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
```

npm-debug.log: https://gist.github.com/leyyinad/3db550282e9526133fc1a29f84482bcd

**Comment by leyyinad** [comment]
Solved it by manually installing `nan` into the correct subdir, like
```bash
cd $(npm root -g)/npm && npm install nan
```

Not the most beautiful, but does the trick for me.

**Comment by shrikrishnaholla** [comment]
> `cd $(npm root -g)/npm && npm install nan`
So `npm` is missing a dependency? I don't get it, why does installing something into npm's `node_modules` fix this problem? @leyyinad how did you figure this out? It is working for me as well...

**Comment by leyyinad** [comment]
I have no idea. I just figured the package was missing and played around a bit. By quickly searching npm's repository I don't see any (even missing) dependency on nan. node-gyp lists nan under `devDependencies`, could this be the reason?

**Comment by shrikrishnaholla** [comment]
It must be `node-gyp`, as the command that throws the error is node-gyp's

**Comment by defunctzombie** [comment]
Nan must be installed locally I believe for this to work. Closing because the package.json should be installing nan so I don't think there is an issue with the module but instead maybe a transient network or install issue that happened. If you find that there is an issue with the module please file a new issue with recommendations on a fix. Thanks!

**Comment by Luna007** [comment]
I have the same error when I do npm install on windows 7. latest npm and node.js

`C:\Users\nliu\WebstormProjects\mdbaas>npm install
npm WARN deprecated node-uuid@1.4.7: use uuid module instead
npm WARN deprecated mongodb@2.1.21: Please upgrade to 2.2.19 or higher
npm WARN deprecated mongodb@2.0.34: Please upgrade to 2.2.19 or higher
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@2.0.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to
find it in the tree.
npm WARN deprecated mongodb@2.1.4: Please upgrade to 2.2.19 or higher
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to
find it in the tree.
npm WARN deprecated CSSselect@0.7.0: the module is now available as 'css-select'
npm WARN deprecated CSSwhat@0.4.7: the module is now available as 'css-what'
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130

> typechecker@2.0.8 preinstall C:\Users\nliu\WebstormProjects\mdbaas\node_modules\.staging\typechecker-f0ce15bb
> node ./cyclic.js

npm WARN prefer global coffee-script@1.9.3 should be installed with -g
npm WARN prefer global marked@0.3.6 should be installed with -g
npm WARN prefer global jsonlint@1.6.2 should be installed with -g
npm WARN prefer global live-server@0.8.2 should be installed with -g
npm WARN prefer global bootprint-json-schema@0.8.6 should be installed with -g
npm WARN prefer global jshint@2.9.4 should be installed with -g
npm WARN prefer global node-gyp@3.4.0 should be installed with -g
npm WARN prefer global babel@5.8.38 should be installed with -g

> kerberos@0.0.22 install C:\Users\nliu\WebstormProjects\mdbaas\node_modules\kerberos
> (node-gyp rebuild) || (exit 0)


C:\Users\nliu\WebstormProjects\mdbaas\node_modules\kerberos>if not defined npm_config_node_gyp (node "C:\Users\nliu\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\
node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
module.js:471
    throw err;
    ^

Error: Cannot find module 'nan'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at [eval]:1:1
    at ContextifyScript.Script.runInThisContext (vm.js:25:33)
    at Object.exports.runInThisContext (vm.js:77:17)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:570:32)
    at Immediate.<anonymous> (bootstrap_node.js:357:29)
gyp: Call to 'node -e "require('nan')"' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\nliu\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:308:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\nliu\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\nliu\WebstormProjects\mdbaas\node_modules\kerberos
gyp ERR! node -v v6.10.0
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok

> bufferutil@1.2.1 install C:\Users\nliu\WebstormProjects\mdbaas\node_modules\bufferutil
> node-gyp rebuild


C:\Users\nliu\WebstormProjects\mdbaas\node_modules\bufferutil>if not defined npm_config_node_gyp (node "C:\Users\nliu\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_module
s\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
module.js:471
    throw err;
    ^

Error: Cannot find module 'nan'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at [eval]:1:1
    at ContextifyScript.Script.runInThisContext (vm.js:25:33)
    at Object.exports.runInThisContext (vm.js:77:17)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:570:32)
    at Immediate.<anonymous> (bootstrap_node.js:357:29)
gyp: Call to 'node -e "require('nan')"' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\nliu\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:308:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\nliu\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\nliu\WebstormProjects\mdbaas\node_modules\bufferutil
gyp ERR! node -v v6.10.0
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok

> ws@0.4.32 install C:\Users\nliu\WebstormProjects\mdbaas\node_modules\grunt-browser-output\node_modules\ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)


C:\Users\nliu\WebstormProjects\mdbaas\node_modules\grunt-browser-output\node_modules\ws>if not defined npm_config_node_gyp (node "C:\Users\nliu\AppData\Roaming\npm\node_modules\npm\bin\node-
gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )

> ws@0.4.32 install C:\Users\nliu\WebstormProjects\mdbaas\node_modules\karma\node_modules\ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)


C:\Users\nliu\WebstormProjects\mdbaas\node_modules\karma\node_modules\ws>if not defined npm_config_node_gyp (node "C:\Users\nliu\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\
node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )

> utf-8-validate@1.2.2 install C:\Users\nliu\WebstormProjects\mdbaas\node_modules\utf-8-validate
> node-gyp rebuild


C:\Users\nliu\WebstormProjects\mdbaas\node_modules\utf-8-validate>if not defined npm_config_node_gyp (node "C:\Users\nliu\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_mo
dules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
module.js:471
    throw err;
    ^

Error: Cannot find module 'nan'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at [eval]:1:1
    at ContextifyScript.Script.runInThisContext (vm.js:25:33)
    at Object.exports.runInThisContext (vm.js:77:17)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:570:32)
    at Immediate.<anonymous> (bootstrap_node.js:357:29)
gyp: Call to 'node -e "require('nan')"' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\nliu\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:308:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\nliu\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\nliu\WebstormProjects\mdbaas\node_modules\utf-8-validate
gyp ERR! node -v v6.10.0
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok

> snappy@5.0.5 install C:\Users\nliu\WebstormProjects\mdbaas\node_modules\snappy
> node-gyp rebuild


C:\Users\nliu\WebstormProjects\mdbaas\node_modules\snappy>if not defined npm_config_node_gyp (node "C:\Users\nliu\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\no
de-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
module.js:471
    throw err;
    ^

Error: Cannot find module 'nan'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at [eval]:1:1
    at ContextifyScript.Script.runInThisContext (vm.js:25:33)
    at Object.exports.runInThisContext (vm.js:77:17)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:570:32)
    at Immediate.<anonymous> (bootstrap_node.js:357:29)
gyp: Call to 'node -e "require('nan')"' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\nliu\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:308:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\nliu\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\nliu\WebstormProjects\mdbaas\node_modules\snappy
gyp ERR! node -v v6.10.0
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok

> phantomjs@1.9.20 install C:\Users\nliu\WebstormProjects\mdbaas\node_modules\phantomjs
> node install.js

PhantomJS not found on PATH
Download already available at C:\Users\nliu\AppData\Local\Temp\phantomjs\phantomjs-1.9.8-windows.zip
Verified checksum of previously downloaded file
Extracting zip contents
Removing C:\Users\nliu\WebstormProjects\mdbaas\node_modules\phantomjs\lib\phantom
Copying extracted folder C:\Users\nliu\AppData\Local\Temp\phantomjs\phantomjs-1.9.8-windows.zip-extract-1488477046842\phantomjs-1.9.8-windows -> C:\Users\nliu\WebstormProjects\mdbaas\node_mo
dules\phantomjs\lib\phantom
Writing location.js file
Done. Phantomjs binary available at C:\Users\nliu\WebstormProjects\mdbaas\node_modules\phantomjs\lib\phantom\phantomjs.exe

> mdbui@2017.1.1 postinstall C:\Users\nliu\WebstormProjects\mdbaas
> grunt install

(node:9788) DeprecationWarning: process.EventEmitter is deprecated. Use require('events') instead.
Running "shell:bower" (shell) task
bower                           ENOENT No bower.json present
Warning: Command failed: bower install
bower                           ENOENT No bower.json present
 Use --force to continue.

Aborted due to warnings.

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^0.3.8 (node_modules\dustjs-linkedin\node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@0.3.8: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN mdbui@2017.1.1 license should be a valid SPDX license expression
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: bufferutil@1.2.1 (node_modules\bufferutil):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: bufferutil@1.2.1 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: utf-8-validate@1.2.2 (node_modules\utf-8-validate):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: utf-8-validate@1.2.2 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: snappy@5.0.5 (node_modules\snappy):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: snappy@5.0.5 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\nliu\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.10.0
npm ERR! npm  v4.3.0
npm ERR! code ELIFECYCLE
npm ERR! errno 6
npm ERR! mdbui@2017.1.1 postinstall: `grunt install`
npm ERR! Exit status 6
npm ERR!
npm ERR! Failed at the mdbui@2017.1.1 postinstall script 'grunt install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the mdbui package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     grunt install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs mdbui
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls mdbui
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\nliu\AppData\Roaming\npm-cache\_logs\2017-03-02T17_51_02_941Z-debug.log`

**Comment by joegreen2** [comment]
```
module.js:471
    throw err;
    ^

Error: Cannot find module 'number-is-nan'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npmlog/node_modules/gauge/node_modules/string-width/node_modules/code-point-at/index.js:2:19)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

if any command at all starts or has anything to do with 'npm' it throws this error

**Comment by danieltanfh95** [comment]
2020 and this works for me.

> Solved it by manually installing `nan` into the correct subdir, like
> 
> ```shell
> cd $(npm root -g)/npm && npm install nan
> ```
> 
> Not the most beautiful, but does the trick for me.
